export const env = {
  NODE_ENV: process.env.NODE_ENV ?? 'development',
  NEXT_PUBLIC_SUPABASE_PROJECT_ID: process.env.NEXT_PUBLIC_SUPABASE_PROJECT_ID!,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL!,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL!,
  APP_URL: process.env.APP_URL!,
  NEXT_PUBLIC_STREAM_API_KEY: process.env.NEXT_PUBLIC_STREAM_API_KEY!,
  NEXT_PUBLIC_BREVO_API_KEY: process.env.NEXT_PUBLIC_BREVO_API_KEY!,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
    process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY!,
  ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,

  NEXT_PUBLIC_ALFRED_AI_SERVICE_BASE_URL:
    process.env.NEXT_PUBLIC_ALFRED_AI_SERVICE_BASE_URL!,
  NEXT_PUBLIC_EXCHANGE_RATE_API_KEY:
    process.env.NEXT_PUBLIC_EXCHANGE_RATE_API_KEY!,
  NEXT_PUBLIC_MEDIA_SERVICE_URL: process.env.NEXT_PUBLIC_MEDIA_SERVICE_URL!,
  NEXT_PUBLIC_MEDIA_SERVICE_API_KEY:
    process.env.NEXT_PUBLIC_MEDIA_SERVICE_API_KEY!,
  NEXT_PUBLIC_HUGGING_FACE_TOKEN: process.env.NEXT_PUBLIC_HUGGING_FACE_TOKEN!,
  NEXT_PUBLIC_STREAM_SECRET_KEY: process.env.NEXT_PUBLIC_STREAM_SECRET_KEY!,
  NEXT_PUBLIC_STRIPE_SECRET_KEY: process.env.NEXT_PUBLIC_STRIPE_SECRET_KEY!,
  NEXT_PUBLIC_STRIPE_WEBHOOK_SECRET:
    process.env.NEXT_PUBLIC_STRIPE_WEBHOOK_SECRET!,
  NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY:
    process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY!,
  NEXT_PUBLIC_UVIVIO_SERVICES_URL: process.env.NEXT_PUBLIC_UVIVIO_SERVICES_URL!,
  NEXT_PUBLIC_UVIVIO_SERVICES_API_KEY:
    process.env.NEXT_PUBLIC_UVIVIO_SERVICES_API_KEY!,
  // Sentry configuration
  NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN!,
  SENTRY_DSN: (process.env.SENTRY_DSN ?? process.env.NEXT_PUBLIC_SENTRY_DSN)!,
  SENTRY_ORG: process.env.SENTRY_ORG!,
  SENTRY_PROJECT: process.env.SENTRY_PROJECT!,
  //
  STREAM_SECRET_KEY: process.env.STREAM_SECRET_KEY!,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET!,
  BREVO_API_KEY: process.env.BREVO_API_KEY!,
  EXCHANGE_RATE_API_KEY: process.env.EXCHANGE_RATE_API_KEY!,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,

  PAYSTACK_BASE_URL: 'https://api.paystack.co',
  PAYSTACK_SECRET_KEY: (process.env.NEXT_PUBLIC_PAYSTACK_SECRET_KEY ??
    process.env.PAYSTACK_SECRET_KEY)!,

  PLAID_BASE_URL: 'https://sandbox.plaid.com',
  PLAID_CLIENT_ID: (process.env.NEXT_PUBLIC_PLAID_CLIENT_ID ??
    process.env.PLAID_CLIENT_ID)!,
  PLAID_SECRET_KEY: (process.env.NEXT_PUBLIC_PLAID_SECRET_KEY ??
    process.env.PLAID_SECRET_KEY)!,

  // Slack configuration
  SENTRY_SLACK_BOT_TOKEN: process.env.SENTRY_SLACK_BOT_TOKEN!,
  SENTRY_SLACK_ERRORS_CHANNEL_ID: process.env.SENTRY_SLACK_ERRORS_CHANNEL_ID!,

  // ClickUp configuration
  CLICKUP_API_TOKEN: process.env.CLICKUP_API_TOKEN!,
  CLICKUP_SUPPORT_LIST_ID: process.env.CLICKUP_SUPPORT_LIST_ID!,
  CLICKUP_WEBHOOK_SECRET: process.env.CLICKUP_WEBHOOK_SECRET!,
};
