/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  author: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'author';
  };
  mainImage: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  categories: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'category';
  }>;
  publishedAt: string;
  readTime?: number;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role?: string;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Post
  | Author
  | Category
  | BlockContent
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: src/sanity/lib/fetch.ts
// Variable: allBlogPostsQuery
// Query: *[_type == "post"] | order(publishedAt desc) {    _id,    title,    slug,    excerpt,    mainImage {      asset,      alt    },    "category": categories[0]-> {      _id,      title,      slug    },    author-> {      name,      role,      image {        asset      }    },    publishedAt,    readTime  }
export type AllBlogPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage: {
    asset: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    } | null;
    alt: string | null;
  };
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  author: {
    name: string;
    role: string | null;
    image: {
      asset: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      } | null;
    };
  };
  publishedAt: string;
  readTime: number | null;
}>;
// Variable: postsByCategoryQuery
// Query: *[_type == "post" && $categorySlug in categories[]->slug.current] | order(publishedAt desc) {    _id,    title,    slug,    excerpt,    mainImage {      asset,      alt    },    "category": categories[0]-> {      _id,      title,      slug    },    author-> {      name,      role,      image {        asset      }    },    publishedAt,    readTime  }
export type PostsByCategoryQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage: {
    asset: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    } | null;
    alt: string | null;
  };
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  author: {
    name: string;
    role: string | null;
    image: {
      asset: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      } | null;
    };
  };
  publishedAt: string;
  readTime: number | null;
}>;
// Variable: searchPostsQuery
// Query: *[_type == "post" && (    title match $searchQuery + "*" ||    excerpt match $searchQuery + "*"  )] | order(publishedAt desc) {    _id,    title,    slug,    excerpt,    mainImage {      asset,      alt    },    "category": categories[0]-> {      _id,      title,      slug    },    author-> {      name,      role,      image {        asset      }    },    publishedAt,    readTime  }
export type SearchPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage: {
    asset: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    } | null;
    alt: string | null;
  };
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  author: {
    name: string;
    role: string | null;
    image: {
      asset: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      } | null;
    };
  };
  publishedAt: string;
  readTime: number | null;
}>;
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    slug,    excerpt,    mainImage {      asset,      alt    },    categories[]-> {      _id,      title,      slug    },    author-> {      name,      role,      image {        asset      },      bio    },    publishedAt,    readTime,    body  }
export type PostBySlugQueryResult = {
  _id: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage: {
    asset: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    } | null;
    alt: string | null;
  };
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }>;
  author: {
    name: string;
    role: string | null;
    image: {
      asset: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      } | null;
    };
    bio: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal';
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }> | null;
  };
  publishedAt: string;
  readTime: number | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'normal';
        listItem?: 'bullet';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  >;
} | null;
// Variable: allCategoriesQuery
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    slug,    description  }
export type AllCategoriesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
}>;
// Variable: relatedPostsQuery
// Query: *[_type == "post" && _id != $postId && $categoryId in categories[]->_id] | order(publishedAt desc) [0...3] {    _id,    title,    slug,    excerpt,    mainImage {      asset,      alt    },    "category": categories[0]-> {      _id,      title,      slug    },    author-> {      name,      role,      image {        asset      }    },    publishedAt,    readTime  }
export type RelatedPostsQueryResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
  excerpt: string;
  mainImage: {
    asset: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    } | null;
    alt: string | null;
  };
  category: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
  author: {
    name: string;
    role: string | null;
    image: {
      asset: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      } | null;
    };
  };
  publishedAt: string;
  readTime: number | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "post"] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage {\n      asset,\n      alt\n    },\n    "category": categories[0]-> {\n      _id,\n      title,\n      slug\n    },\n    author-> {\n      name,\n      role,\n      image {\n        asset\n      }\n    },\n    publishedAt,\n    readTime\n  }\n': AllBlogPostsQueryResult;
    '\n  *[_type == "post" && $categorySlug in categories[]->slug.current] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage {\n      asset,\n      alt\n    },\n    "category": categories[0]-> {\n      _id,\n      title,\n      slug\n    },\n    author-> {\n      name,\n      role,\n      image {\n        asset\n      }\n    },\n    publishedAt,\n    readTime\n  }\n': PostsByCategoryQueryResult;
    '\n  *[_type == "post" && (\n    title match $searchQuery + "*" ||\n    excerpt match $searchQuery + "*"\n  )] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage {\n      asset,\n      alt\n    },\n    "category": categories[0]-> {\n      _id,\n      title,\n      slug\n    },\n    author-> {\n      name,\n      role,\n      image {\n        asset\n      }\n    },\n    publishedAt,\n    readTime\n  }\n': SearchPostsQueryResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage {\n      asset,\n      alt\n    },\n    categories[]-> {\n      _id,\n      title,\n      slug\n    },\n    author-> {\n      name,\n      role,\n      image {\n        asset\n      },\n      bio\n    },\n    publishedAt,\n    readTime,\n    body\n  }\n': PostBySlugQueryResult;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    slug,\n    description\n  }\n': AllCategoriesQueryResult;
    '\n  *[_type == "post" && _id != $postId && $categoryId in categories[]->_id] | order(publishedAt desc) [0...3] {\n    _id,\n    title,\n    slug,\n    excerpt,\n    mainImage {\n      asset,\n      alt\n    },\n    "category": categories[0]-> {\n      _id,\n      title,\n      slug\n    },\n    author-> {\n      name,\n      role,\n      image {\n        asset\n      }\n    },\n    publishedAt,\n    readTime\n  }\n': RelatedPostsQueryResult;
  }
}
